name: MLflow Training Workflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pandas
          pip install scikit-learn
          pip install matplotlib
          pip install mlflow
          pip install joblib

      - name: Run Training
        working-directory: MLProject
        run: |
          python modelling.py